const arr = [
  {
    title: 'js w3',
    img: '/assets/media/bg1.jpg',
    details: `JavaScript is the programming language of the Web. JavaScript is easy to learn. This tutorial covers everything from basic JavaScript up to the latest 2025 version.`,
    links: 'https://www.w3schools.com/js/default.asp',
    type: 'js',
  },
  {
    title: 'Python Official',
    img: '/assets/media/bg2.jpg',
    details: `Python is a powerful and versatile programming language. It is widely used for automation, data analysis, and web development.`,
    links: 'https://docs.python.org/3/',
    type: 'python',
  },
  {
    title: 'HTML Introduction',
    img: '/assets/media/bg3.jpg',
    details: `HTML is the foundation of all web pages. This guide will teach you how to structure content on the web.`,
    links: 'https://www.w3schools.com/html/',
    type: 'html',
  },
  {
    title: 'CSS Essentials',
    img: '/assets/media/bg4.jpg',
    details: `CSS is used to style and layout web pages. Learn how to make your pages visually appealing.`,
    links: 'https://www.w3schools.com/css/',
    type: 'css',
  },
  {
    title: 'React Fundamentals',
    img: '/assets/media/bg5.jpg',
    details: `React is a JavaScript library for building modern UIs. Start with components, props, and state.`,
    links: 'https://reactjs.org/',
    type: 'react',
  },
  {
    title: 'Modern JavaScript',
    img: '/assets/media/bg6.jpg',
    details: `Master ES6+ JavaScript features such as let/const, arrow functions, and promises.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    type: 'js',
  },
  {
    title: 'Python for Beginners',
    img: '/assets/media/bg7.jpg',
    details: `An easy introduction to Python programming for complete beginners.`,
    links: 'https://realpython.com/python-basics/',
    type: 'python',
  },
  {
    title: 'Advanced CSS Tricks',
    img: '/assets/media/bg8.jpg',
    details: `Explore flexbox, grid, animations, and custom properties in CSS.`,
    links: 'https://css-tricks.com/',
    type: 'css',
  },
  {
    title: 'HTML5 Features',
    img: '/assets/media/bg9.jpg',
    details: `Learn about new semantic elements and APIs introduced in HTML5.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5',
    type: 'html',
  },
  {
    title: 'React Hooks',
    img: '/assets/media/bg10.jpg',
    details: `Master useState, useEffect, and custom hooks in React.`,
    links: 'https://reactjs.org/docs/hooks-intro.html',
    type: 'react',
  },
  {
    title: 'JavaScript Arrays',
    img: '/assets/media/bg1.jpg',
    details: `Understand how to work with arrays using map, filter, reduce, and more.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array',
    type: 'js',
  },
  {
    title: 'Python OOP',
    img: '/assets/media/bg2.jpg',
    details: `Learn object-oriented programming in Python: classes, inheritance, and polymorphism.`,
    links: 'https://realpython.com/python3-object-oriented-programming/',
    type: 'python',
  },
  {
    title: 'HTML Forms',
    img: '/assets/media/bg3.jpg',
    details: `Build interactive forms and handle user input using HTML.`,
    links: 'https://www.w3schools.com/html/html_forms.asp',
    type: 'html',
  },
  {
    title: 'CSS Grid Layout',
    img: '/assets/media/bg4.jpg',
    details: `CSS Grid makes two-dimensional layout easy. Learn how to create flexible layouts.`,
    links: 'https://css-tricks.com/snippets/css/complete-guide-grid/',
    type: 'css',
  },
  {
    title: 'React State Management',
    img: '/assets/media/bg5.jpg',
    details: `Manage application state efficiently using React context and external libraries.`,
    links: 'https://redux.js.org/',
    type: 'react',
  },
  {
    title: 'ES6 Modules',
    img: '/assets/media/bg6.jpg',
    details: `Learn how to structure JavaScript using modules, import/export syntax, and bundlers.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules',
    type: 'js',
  },
  {
    title: 'Python Automation',
    img: '/assets/media/bg7.jpg',
    details: `Automate boring tasks using Python and libraries like Selenium or PyAutoGUI.`,
    links: 'https://automatetheboringstuff.com/',
    type: 'python',
  },
  {
    title: 'HTML Media',
    img: '/assets/media/bg8.jpg',
    details: `Embed audio, video, and media content in web pages using HTML.`,
    links: 'https://www.w3schools.com/html/html_media.asp',
    type: 'html',
  },
  {
    title: 'CSS Transitions',
    img: '/assets/media/bg9.jpg',
    details: `Add smooth transitions to your CSS elements to enhance UX.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_transitions/Using_CSS_transitions',
    type: 'css',
  },
  {
    title: 'React Router',
    img: '/assets/media/bg10.jpg',
    details: `Implement routing in React applications using React Router.`,
    links: 'https://reactrouter.com/',
    type: 'react',
  },
  {
    title: 'JS Event Handling',
    img: '/assets/media/bg1.jpg',
    details: `Learn how to handle user interactions using JavaScript events.`,
    links: 'https://www.w3schools.com/js/js_events.asp',
    type: 'js',
  },
  {
    title: 'Python Data Science',
    img: '/assets/media/bg2.jpg',
    details: `Use Python libraries like pandas, NumPy, and Matplotlib for data analysis.`,
    links: 'https://www.datacamp.com/',
    type: 'python',
  },
  {
    title: 'HTML Tables',
    img: '/assets/media/bg3.jpg',
    details: `Design and structure tabular data using HTML tables.`,
    links: 'https://www.w3schools.com/html/html_tables.asp',
    type: 'html',
  },
  {
    title: 'CSS Flexbox',
    img: '/assets/media/bg4.jpg',
    details: `Flexbox simplifies layout. Master alignment, spacing, and responsiveness.`,
    links: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/',
    type: 'css',
  },
  {
    title: 'React Forms',
    img: '/assets/media/bg5.jpg',
    details: `Handle forms, validation, and state in React apps effectively.`,
    links: 'https://reactjs.org/docs/forms.html',
    type: 'react',
  },
  {
    title: 'JavaScript Functions',
    img: '/assets/media/bg6.jpg',
    details: `Learn about function declarations, expressions, arrow functions, and closures.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions',
    type: 'js',
  },
  {
    title: 'Python with Flask',
    img: '/assets/media/bg7.jpg',
    details: `Build lightweight web applications using the Flask framework in Python.`,
    links: 'https://flask.palletsprojects.com/',
    type: 'python',
  },
  {
    title: 'HTML Semantic Tags',
    img: '/assets/media/bg8.jpg',
    details: `Use semantic HTML tags like <header>, <section>, and <article> to improve accessibility.`,
    links: 'https://developer.mozilla.org/en-US/docs/Glossary/Semantics',
    type: 'html',
  },
  {
    title: 'CSS Variables',
    img: '/assets/media/bg9.jpg',
    details: `Write maintainable CSS using custom properties (variables).`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/CSS/--*',
    type: 'css',
  },
  {
    title: 'React Components',
    img: '/assets/media/bg10.jpg',
    details: `Understand how to build reusable UI pieces using React components.`,
    links: 'https://reactjs.org/docs/components-and-props.html',
    type: 'react',
  },
    {
    title: 'JS Error Handling',
    img: '/assets/media/bg1.jpg',
    details: `Learn how to handle errors gracefully in JavaScript using try...catch, finally, and error objects.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling',
    type: 'js',
  },
  {
    title: 'Python with Django',
    img: '/assets/media/bg2.jpg',
    details: `Build robust, scalable web applications using the Django web framework in Python.`,
    links: 'https://www.djangoproject.com/',
    type: 'python',
  },
  {
    title: 'HTML Accessibility',
    img: '/assets/media/bg3.jpg',
    details: `Make your websites accessible with ARIA roles, semantic tags, and keyboard navigation.`,
    links: 'https://www.w3.org/WAI/fundamentals/accessibility-intro/',
    type: 'html',
  },
  {
    title: 'CSS Pseudo Elements',
    img: '/assets/media/bg4.jpg',
    details: `Enhance your UI using ::before, ::after, and other pseudo-elements in CSS.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements',
    type: 'css',
  },
  {
    title: 'React Lifecycle Methods',
    img: '/assets/media/bg5.jpg',
    details: `Learn how class and functional components handle lifecycle events in React.`,
    links: 'https://reactjs.org/docs/react-component.html',
    type: 'react',
  },
  {
    title: 'JavaScript Promises',
    img: '/assets/media/bg6.jpg',
    details: `Handle asynchronous operations in JavaScript using promises and async/await.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises',
    type: 'js',
  },
  {
    title: 'Python File Handling',
    img: '/assets/media/bg7.jpg',
    details: `Read, write, and manage files in Python efficiently with context managers.`,
    links: 'https://realpython.com/read-write-files-python/',
    type: 'python',
  },
  {
    title: 'HTML5 APIs',
    img: '/assets/media/bg8.jpg',
    details: `Explore powerful HTML5 APIs such as geolocation, local storage, and canvas.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/API',
    type: 'html',
  },
  {
    title: 'CSS Media Queries',
    img: '/assets/media/bg9.jpg',
    details: `Build responsive layouts using media queries in CSS for all screen sizes.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries',
    type: 'css',
  },
  {
    title: 'React Performance',
    img: '/assets/media/bg10.jpg',
    details: `Improve your React app's performance using memoization, lazy loading, and code splitting.`,
    links: 'https://reactjs.org/docs/optimizing-performance.html',
    type: 'react',
  },
  {
    title: 'JavaScript DOM',
    img: '/assets/media/bg1.jpg',
    details: `Manipulate the Document Object Model (DOM) using JavaScript to create dynamic content.`,
    links: 'https://www.w3schools.com/js/js_htmldom.asp',
    type: 'js',
  },
  {
    title: 'Python Exception Handling',
    img: '/assets/media/bg2.jpg',
    details: `Handle runtime errors in Python using try-except blocks and custom exceptions.`,
    links: 'https://realpython.com/python-exceptions/',
    type: 'python',
  },
  {
    title: 'HTML Meta Tags',
    img: '/assets/media/bg3.jpg',
    details: `Optimize your webpages for SEO and social sharing using HTML meta tags.`,
    links: 'https://www.w3schools.com/tags/tag_meta.asp',
    type: 'html',
  },
  {
    title: 'CSS Z-Index',
    img: '/assets/media/bg4.jpg',
    details: `Control stacking order of elements in CSS using the z-index property.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/CSS/z-index',
    type: 'css',
  },
  {
    title: 'React Props',
    img: '/assets/media/bg5.jpg',
    details: `Pass data between components in React using props and prop-types.`,
    links: 'https://reactjs.org/docs/components-and-props.html',
    type: 'react',
  },
  {
    title: 'JavaScript Objects',
    img: '/assets/media/bg6.jpg',
    details: `Learn about object creation, inheritance, and manipulation in JavaScript.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects',
    type: 'js',
  },
  {
    title: 'Python Lists',
    img: '/assets/media/bg7.jpg',
    details: `Master Python lists with slicing, comprehension, and built-in functions.`,
    links: 'https://docs.python.org/3/tutorial/datastructures.html',
    type: 'python',
  },
  {
    title: 'HTML Entities',
    img: '/assets/media/bg8.jpg',
    details: `Use HTML entities to display reserved characters in your content.`,
    links: 'https://www.w3schools.com/html/html_entities.asp',
    type: 'html',
  },
  {
    title: 'CSS Shadows',
    img: '/assets/media/bg9.jpg',
    details: `Add depth and effects to elements using box-shadow and text-shadow in CSS.`,
    links: 'https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow',
    type: 'css',
  },
  {
    title: 'React UseEffect',
    img: '/assets/media/bg10.jpg',
    details: `Use the useEffect hook in React to perform side effects in function components.`,
    links: 'https://reactjs.org/docs/hooks-effect.html',
    type: 'react',
  }

  // Continue generating up to 50...
  // Skipping actual writing here to save space.
];